### ISSUE TITLE
API change in cucumber-js v0.7.0 broke cucumber-assert

### ISSUE THREAD

**Issue by romanek-adam** [djungowski/cucumber-assert#2]
Please see cucumber/cucumber-js/issues/437.

**Comment by djungowski** [comment]
I just released version 1.0.2 which supports cucumber.js >= 0.7.0. I also added integration tests in the process. Please let me know if version 1.0.2 fixes your problem.

**Comment by romanek-adam** [comment]
Yes, v1.0.2 fixes my problem. Thank you!
