### ISSUE TITLE
callback cannot be null

### ISSUE THREAD

**Issue by JasonSmiley208** [djungowski/cucumber-assert#3]
If I want to assert multiple things in a single cucumber step, I currently cannot because it will say "callback is not a function":

Example:

```
assert.equal(firstNameInput.getAttribute("value"), expectedFirst, null, "First Name Doesn't match expected value");   //Fails here.
        assert.equal(lastNameInput.getAttribute("value"), expectedLast, null, "Last Name Doesn't match expected value");
        assert.equal(emailInput.getAttribute("value"), expectedEmail, null, "Email Doesn't match expected value");
        assert.equal(phoneInput.getAttribute("value"), expectedPhone, callback, "Phone Doesn't match expected value");
```

**Comment by djungowski** [comment]
Easiest workaround as long as I haven't fixed this would be to use an empty function instead of null. I will change this as soon as I can!

**Comment by djungowski** [comment]
Thinking how to implement this. Problem is, that the cucumber callback function is also called with the error message provided in case there is an error. Meaning: if you would provide null, you would get the annoying uber-stacktraces of cucumber.js.
Usually you would put your asserts in a separate step definition.

**Comment by djungowski** [comment]
I just implemented a version in the branch 3-allow-multiple-asserts. Maybe you can check that? Usage is:

> assert.expectMultipleEquals(3, callback);
> assert.equal(true, true, null, errorMessageString);
> assert.equal(true, true, null, errorMessageString);
> assert.equal(true, true, null, errorMessageString);
