### ISSUE TITLE
make callback on success optional

### ISSUE THREAD

**Issue by BasHamer** [djungowski/cucumber-assert#4]
so one thing to call out is that if you don't do a single assert you get multiple callbacks. 

I have some small steps about setting up a new user to check in detail if the bits work; for future steps I just have "Given a new logged in user" and then do the 4 rest calls behind the scene. I found out that doing this meant that my user was still running as a zombie behind the scenes while it had already gone on to future steps.

It would be nice if there was an option that only called the callback on a failure vs all the time. even better if it was configurable on the class itself.

**Comment by BasHamer** [comment]
optionally if you want you can do 
Assert.expectMultipleAssertions
followed by a 
Assert.MultipleAssertionsComplete
And in between it only calls the callback on failed assertions.

**Comment by djungowski** [comment]
So, if I get you right, you would like to be able to run assertions which only call the callback if there is an error? Something like

``` javascript
assert.proceed.equal(fieldValue, email, callback, 'Expected E-Mail to be ' + email);
```

?

**Comment by sebs** [comment]
That sounds like more of a idea that I would have had when I started to test. an you elaborate on this with a code example? ;)

**Comment by BasHamer** [comment]
I have a flow that signs up a new user, this is broken down into 5 steps in it's own feature;

Then when I test other features I have one step that states "given a new logged in user" that does all these calls in the background. 

my rest calls already live outside of my steps, and I want to reuse the same rest calls for both the detailed login, and the short hand login. 

I realize that I can repeat all the login steps in the background but that leads to a lot of duplication as every feature other than the original needs a logged in user. 

now when someone else goes into that code and the update the asserts to add a check to verify a field is not null (where as before it just verified a 200) my counts need to be updated multiple places. This would not cause an error, it would create a race condition and flaky tests over time. 

I also assert the response is correct and after that I want to store a token for future steps. Ideally my callback would not happen until my token is stored, but the assertion happens before the token is stored.

if you want actual code let me know and I can annonomize some.

**Comment by djungowski** [comment]
I realize that this issue is quite old but some actual code would be nice, if this problem still persists on your side

**Comment by BasHamer** [comment]
Actual code won't work at this point, unfortunately; but I can provide a sample

```
Feature: sample
Scenario: detailed
When Creating user
And Updating security question 1
And updating security question 2
Then I have a  valid user created
And the user has security questions

Scenario: shortcut
Given a user with security questions setup
Then I have a valid user
```


for the method of "Given a user with security questions setup" I want to call the methods that are called by the detailed scenario. unfortunately, if someone added an assert to any of these methods then you can get an errant callback and security questions don't get set up all the way. 

The way that the system tends to evolve is that there are detailed steps making sure that individual features are working, and then other scenarios aggregate some of these steps to get to their scenarios. So there is detailed **user** setup, but when you get to the **reports** module of the application you are testing then your **user** steps tend to get condensed as much as possible (sometimes down to an attribute). This means your call hierarchy of steps calling steps can get up to 3-4 levels deep.  These aggregate steps tend to involve assertions as you want clear error messages; if the user module does not work I want my report module to say "failed to create a user" vs. "Object reference not set to an instance of an object". When we discover new failure modes more of these assertions get added, and when you have a function hierarchy that gets wonky if you have to maintain counts.

Now I realize that cucumber.js has had a pretty big update since then, so I don't know how applicable this problem is anymore. 

In the end, we moved to a different assertion framework, so the problem is "solved" but this was the reason we went to the other framework.

**Comment by djungowski** [comment]
Closing since it does not seem to be relevant anymore
