### ISSUE TITLE
Make cucumber-assert compatible with promises

### ISSUE THREAD

**Issue by metareven** [djungowski/cucumber-assert#6]
As it is right now cucumber-assert is not compatible with promises since the asserts do not return promises and also requires you to specify a callback, giving you the `function uses multiple asynchronous interfaces: callback and promise` error.

It would be nice if asserts returned promises so that you could use them in a promise chain

**Comment by djungowski** [comment]
@metareven I just pushed the branch [promises](https://github.com/djungowski/cucumber-assert/tree/promises) where every assert returns a promise + there is a shorthand for Promise.all. Could you please test it and tell me if it works for you?

**Comment by sebs** [comment]
Promise.race ?

**Comment by metareven** [comment]
Seems to work nicely for my use case at least!

**Comment by djungowski** [comment]
Ok, great. Then I will merge it into the master and publish a new version via NPM
