### ISSUE TITLE
Odd code version

### ISSUE THREAD

**Issue by nickcodefresh** [djungowski/cucumber-assert#9]
Hi,

I'm installing 2.0.0 v ia npm but the code index.js is

```
	notEqual(actual, expected, message) {
		this.callActualEqualAssert('notEqual', actual, expected, message);
	}
```

whereas on master in GitHub it's 

```
        notEqual(actual, expected, message) {
		return this.callActualEqualAssert('notEqual', actual, expected, message);
	}
```

Any idea why?

Nick

**Comment by romaharevich** [comment]
Hi Nick,

2.0.0 version still haven't latest commits. It will be great if code owner release 2.0.1 (or something) with latest version.

For now I have to use my fork as workaround(.

Best regards,
Roma

**Comment by djungowski** [comment]
Looks like I forgot to release a new version. I will publish 2.0.1 in a minute

**Comment by djungowski** [comment]
I just released a new version 2.0.1 which should have the latest code version. Thanks for letting me know! :)

**Comment by sebs** [comment]
maybe add a autorelease after pushing a new version number. This turned out to be very productive.

**Comment by sebs** [comment]
ah you can use release-it as well ;)
